### ISSUE TITLE
Issue running tf-recurrent-sin-5.1.py

### ISSUE THREAD

**Issue by kissste** [sunsided/tensorflow-lstm-sin#2]
"ValueError: Trying to share variable rnn/multi_rnn_cell/cell_0/basic_lstm_cell/kernel, but specified shape (20, 40) and found shape (11, 40)."

on python 3.5 with tensorflow_gpu-1.3.0

**Comment by PiotrGrzybowski** [comment]
Hi @kissste 
Did you figure out the problem? I have the same

**Comment by PiotrGrzybowski** [comment]
@sunsided @kissste 
https://github.com/udacity/deep-learning/issues/132 Resolves the Issue, this is because of newer version of tensorflow

**Comment by sunsided** [comment]
Heh, I'm only glad the Udacity code base does the same stupid things. I even had to patch some unit tests from them in order to work with newer TensorFlow versions. It's almost a shame the early versions didn't complain as much as the newer ones do. Anyway, I'll merge a fix for this in a couple of minutes.
